 const autoex1 ={
    clogin: '[href="/login"]',
    row: '[class="row"]',
    logf: '[class="login-form"]',
    signf: '[class="signup-form"]',
    signu: '[data-qa="signup-name"]',
    email: '[data-qa="signup-email"]',
    button:'[data-qa="signup-button"]',
    signfr: '[class="login-form"]',
    text: 'Enter Account Information',
    check: '[class="clearfix"]',
    gender1: '[for="id_gender1"]',
    gender2: '[for="id_gender2"]',
    name: '[id="name"]',
    email2: '[id="email"]',
    passw: '[data-qa="password"]',
    DOB: '[class="form-group"]',
    day:'[id="days"]',
    month: '[id="months"]',
    year: '[id="years"]',
    news: '[class="checkbox"]',
    partner: '[id="uniform-optin"]',
    adtext: '[class="title text-center"]',
    fir: '[data-qa="first_name"]',
    las: '[data-qa="last_name"]',
    com: '[data-qa="company"]',
    ad: '[class="inline-infos"]',
    ad1:'[data-qa="address"]',
    ad2: '[data-qa="address2"]',
    con: '[id="country"]',
    state: '[data-qa="state"]',
    city: '[data-qa="city"]',
    zip: '[data-qa="zipcode"]',
    Mobile: '[data-qa="mobile_number"]',
    creacc: '[data-qa="create-account"]',
    ref: '[data-qa="account-created"]'
 }
 export default autoex1